# Generated by Django 6.0.2 on 2026-02-20 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
        ('candidates', '0001_initial'),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='fully_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='candidate',
            name='fully_paid_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='initial_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total amount to be paid', max_digits=10),
        ),
        migrations.AddField(
            model_name='candidate',
            name='loan_provider',
            field=models.CharField(blank=True, help_text='If on loan, name of provider', max_length=100),
        ),
        migrations.AddField(
            model_name='candidate',
            name='loan_reference',
            field=models.CharField(blank=True, help_text='Loan reference number', max_length=100),
        ),
        migrations.AddField(
            model_name='candidate',
            name='payment_plan',
            field=models.CharField(choices=[('cash', 'Full Cash Payment'), ('loan', 'Loan'), ('installment', 'Installment Plan')], default='cash', max_length=20),
        ),
        migrations.AddField(
            model_name='candidate',
            name='remaining_balance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Remaining balance to be paid', max_digits=10),
        ),
        migrations.AddField(
            model_name='candidate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['fully_paid'], name='candidates__fully_p_3dc09d_idx'),
        ),
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['payment_plan'], name='candidates__payment_b77ba4_idx'),
        ),
    ]
