# Generated by Django 6.0.2 on 2026-03-04 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0002_candidate_fully_paid_candidate_fully_paid_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='nationality',
            field=models.CharField(choices=[('UG', 'Ugandan'), ('KE', 'Kenyan'), ('TZ', 'Tanzanian'), ('RW', 'Rwandan'), ('BI', 'Burundian'), ('SS', 'South Sudanese'), ('NG', 'Nigerian'), ('GH', 'Ghanaian'), ('ZA', 'South African'), ('CM', 'Cameroonian'), ('CI', 'Ivorian'), ('SN', 'Senegalese'), ('ET', 'Ethiopian'), ('ER', 'Eritrean'), ('SO', 'Somali'), ('CD', 'Congolese (DRC)'), ('CG', 'Congolese (Brazzaville)'), ('EG', 'Egyptian'), ('MA', 'Moroccan'), ('TN', 'Tunisian'), ('DZ', 'Algerian'), ('LY', 'Libyan'), ('SD', 'Sudanese'), ('Other', 'Other')], default='UG', help_text="Candidate's nationality", max_length=50),
        ),
    ]
