# Generated by Django 6.0.2 on 2026-03-04 09:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('finance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_income', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_capital', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('closing_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cash Position',
                'verbose_name_plural': 'Cash Positions',
                'ordering': ['-date'],
            },
        ),
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-date'], 'verbose_name': 'Expense', 'verbose_name_plural': 'Expenses'},
        ),
        migrations.AlterModelOptions(
            name='income',
            options={'ordering': ['-date'], 'verbose_name': 'Income', 'verbose_name_plural': 'Income Records'},
        ),
        migrations.AddField(
            model_name='expense',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('cheque', 'Cheque'), ('mobile_money', 'Mobile Money'), ('credit_card', 'Credit Card'), ('other', 'Other')], default='cash', max_length=20),
        ),
        migrations.AddField(
            model_name='expense',
            name='reference',
            field=models.CharField(blank=True, help_text='Invoice/Receipt number', max_length=100),
        ),
        migrations.AddField(
            model_name='expense',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='income',
            name='income_type',
            field=models.CharField(choices=[('client_payment', '💰 Client Payment'), ('capital_injection', '🏦 Capital Injection / Owner Investment'), ('loan', '💳 Loan'), ('other', '📦 Other Income')], default='client_payment', max_length=20),
        ),
        migrations.AddField(
            model_name='income',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('cheque', 'Cheque'), ('mobile_money', 'Mobile Money'), ('other', 'Other')], default='cash', max_length=20),
        ),
        migrations.AddField(
            model_name='income',
            name='receipt',
            field=models.FileField(blank=True, null=True, upload_to='income_receipts/'),
        ),
        migrations.AddField(
            model_name='income',
            name='reference',
            field=models.CharField(blank=True, help_text='Receipt/Invoice/Reference number', max_length=100),
        ),
        migrations.AddField(
            model_name='income',
            name='source',
            field=models.CharField(blank=True, help_text='Source of capital (e.g., Owner, Investor, Bank)', max_length=100),
        ),
        migrations.AddField(
            model_name='income',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('salary', '💼 Salary'), ('office_rent', '🏢 Office Rent'), ('utilities', '💡 Utilities'), ('travel', '✈️ Travel'), ('marketing', '📢 Marketing'), ('office_supplies', '📎 Office Supplies'), ('equipment', '🖥️ Equipment'), ('professional_fees', '⚖️ Professional Fees'), ('taxes', '📊 Taxes'), ('loan_repayment', '💳 Loan Repayment'), ('capital_withdrawal', '🏧 Owner Withdrawal'), ('other', '📦 Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='income',
            name='client',
            field=models.ForeignKey(blank=True, help_text='Required for client payments, leave blank for capital/loans', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incomes', to='clients.client'),
        ),
        migrations.CreateModel(
            name='CapitalInjection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('source_type', models.CharField(choices=[('owner', 'Owner Investment'), ('shareholder', 'Shareholder Investment'), ('loan', 'Loan'), ('other', 'Other')], default='owner', max_length=20)),
                ('source_name', models.CharField(help_text='Name of investor/lender', max_length=100)),
                ('reference', models.CharField(blank=True, help_text='Agreement/Reference number', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('receipt', models.FileField(blank=True, null=True, upload_to='capital_receipts/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('received_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capital_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Capital Injection',
                'verbose_name_plural': 'Capital Injections',
                'ordering': ['-date'],
            },
        ),
    ]
