# Generated by Django 6.0.2 on 2026-02-20 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medical_report', models.BooleanField(default=False)),
                ('interpol', models.BooleanField(default=False)),
                ('passport_copy', models.BooleanField(default=False)),
                ('passport_photo', models.BooleanField(default=False)),
                ('offer_letter', models.BooleanField(default=False)),
                ('signed_offer_letter', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='candidates.candidate')),
            ],
        ),
    ]
