# Generated by Django 6.0.2 on 2026-02-20 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentstatus',
            name='signed_offer_letter',
        ),
        migrations.AddField(
            model_name='documentstatus',
            name='mol_approval',
            field=models.BooleanField(default=False, verbose_name='MOL Approval Received and Signed'),
        ),
    ]
