# Generated by Django 6.0.2 on 2026-03-02 16:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0002_candidate_fully_paid_candidate_fully_paid_date_and_more'),
        ('documents', '0002_remove_documentstatus_signed_offer_letter_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='candidate_documents/%Y/%m/%d/')),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size', models.IntegerField(default=0)),
                ('file_type', models.CharField(max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.IntegerField(default=1)),
                ('is_latest', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Candidate Document',
                'verbose_name_plural': 'Candidate Documents',
                'ordering': ['document_type__order', '-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('required', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Document Type',
                'verbose_name_plural': 'Document Types',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MergedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='merged_documents/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Merged Document',
                'verbose_name_plural': 'Merged Documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='documentstatus',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Document Status', 'verbose_name_plural': 'Document Statuses'},
        ),
        migrations.AlterField(
            model_name='documentstatus',
            name='candidate',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='document_status', to='candidates.candidate'),
        ),
        migrations.AddIndex(
            model_name='documentstatus',
            index=models.Index(fields=['candidate'], name='documents_d_candida_27d1c9_idx'),
        ),
        migrations.AddIndex(
            model_name='documentstatus',
            index=models.Index(fields=['updated_at'], name='documents_d_updated_83feaf_idx'),
        ),
        migrations.AddField(
            model_name='candidatedocument',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_documents', to='candidates.candidate'),
        ),
        migrations.AddField(
            model_name='candidatedocument',
            name='previous_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_versions', to='documents.candidatedocument'),
        ),
        migrations.AddField(
            model_name='candidatedocument',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='candidatedocument',
            name='document_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_documents', to='documents.documenttype'),
        ),
        migrations.AddField(
            model_name='mergeddocument',
            name='candidate',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='merged_document', to='candidates.candidate'),
        ),
        migrations.AddField(
            model_name='mergeddocument',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_merged_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mergeddocument',
            name='document_types',
            field=models.ManyToManyField(related_name='merged_documents', to='documents.documenttype'),
        ),
        migrations.AddIndex(
            model_name='candidatedocument',
            index=models.Index(fields=['candidate', 'document_type'], name='documents_c_candida_0a084c_idx'),
        ),
        migrations.AddIndex(
            model_name='candidatedocument',
            index=models.Index(fields=['is_latest'], name='documents_c_is_late_7c198a_idx'),
        ),
    ]
