"""
Django settings for globis_hr project.
Generated by 'django-admin startproject' using Django 4.2.
"""

import os
from pathlib import Path
from django.core.management.utils import get_random_secret_key
import environ
import dj_database_url
import logging

# Build paths
BASE_DIR = Path(__file__).resolve().parent.parent

# Initialize environ
env = environ.Env(
    DEBUG=(bool, False),
    SECRET_KEY=(str, get_random_secret_key()),
    ALLOWED_HOSTS=(list, []),
    CSRF_TRUSTED_ORIGINS=(list, []),
    DATABASE_URL=(str, f'sqlite:///{BASE_DIR}/db.sqlite3'),
)

# Check for mounted secrets in Cloud Run
secrets_path = '/secrets/django-settings'
if os.path.exists(secrets_path):
    env.read_env(secrets_path)
    print(f"Loaded secrets from {secrets_path}")
else:
    env_file = BASE_DIR / '.env'
    if env_file.exists():
        env.read_env(str(env_file))
        print(f"Loaded secrets from {env_file}")
    else:
        print("No secret file found, using environment variables")

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG')

ALLOWED_HOSTS = env('ALLOWED_HOSTS')
CSRF_TRUSTED_ORIGINS = env('CSRF_TRUSTED_ORIGINS')

# Cloud Run specific settings
if 'K_SERVICE' in os.environ:
    # Add .run.app domain to allowed hosts
    ALLOWED_HOSTS.append('.run.app')
    
    # Add your specific Cloud Run URL to CSRF trusted origins
    current_url = f"https://{os.environ.get('K_SERVICE')}-{os.environ.get('RUN_ID', '')}.run.app"
    CSRF_TRUSTED_ORIGINS.append(current_url)
    CSRF_TRUSTED_ORIGINS.append('https://*.run.app')
    
    # Security settings for Cloud Run
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    CSRF_COOKIE_HTTPONLY = False  # Important: Must be False for CSRF token to work with AJAX
    CSRF_COOKIE_SAMESITE = 'Lax'
    CSRF_USE_SESSIONS = False  # Use cookies instead of sessions for CSRF
    SESSION_COOKIE_SAMESITE = 'Lax'
    
    print(f"Running on Cloud Run service: {os.environ.get('K_SERVICE')}")
    print(f"CSRF Trusted Origins: {CSRF_TRUSTED_ORIGINS}")

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Third-party apps
    'django.contrib.humanize',
    
    # Custom apps
    'apps.accounts',
    'apps.clients',
    'apps.agents',
    'apps.candidates',
    'apps.documents',
    'apps.visa_process',
    'apps.candidate_payments',
    'apps.placements',
    'apps.finance',
    'apps.reports',
    'apps.imports',
    'django_ckeditor_5',  # Only CKEditor 5
    'apps.jobs.apps.JobsConfig',
]

# Remove all CKEditor 4 configurations
# Only keep CKEditor 5 configuration

CKEDITOR_5_CONFIGS = {
    'default': {
        'toolbar': ['heading', '|', 'bold', 'italic', 'link',
                   'bulletedList', 'numberedList', 'blockQuote', '|',
                   'undo', 'redo'],
        'height': '300px',
        'width': '100%',
    },
    'extends': {
        'toolbar': ['heading', '|', 'bold', 'italic', 'link', 'underline',
                   'strikethrough', 'subscript', 'superscript', '|',
                   'bulletedList', 'numberedList', '|',
                   'alignment', 'outdent', 'indent', '|',
                   'blockQuote', 'insertTable', '|',
                   'undo', 'redo'],
        'height': '400px',
        'width': '100%',
    },
}

CKEDITOR_5_FILE_UPLOAD_PERMISSION = "staff"  # or "authenticated"

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',  # This must be here
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'globis_hr.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'apps.accounts.context_processors.user_permissions',
            ],
        },
    },
]

WSGI_APPLICATION = 'globis_hr.wsgi.application'

# Database
DATABASES = {
    'default': dj_database_url.config(
        default=env('DATABASE_URL'),
        conn_max_age=600,
        conn_health_checks=True,
    )
}

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {'min_length': 8},
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

handler403 = 'apps.accounts.views.custom_403_view'
handler404 = 'apps.accounts.views.custom_404_view'
handler500 = 'apps.accounts.views.custom_500_view'

# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Africa/Kampala'
USE_I18N = True
USE_TZ = True

# Static files
STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# File upload settings
FILE_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024  # 10MB
DATA_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024
FILE_UPLOAD_PERMISSIONS = 0o644

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Login URL
LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/dashboard/'
LOGOUT_REDIRECT_URL = '/accounts/login/'

# Session settings
SESSION_COOKIE_AGE = 1209600
SESSION_COOKIE_NAME = 'globis_session'
SESSION_SAVE_EVERY_REQUEST = True

# Email settings (optional)
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = env('EMAIL_HOST', default='smtp.gmail.com')
EMAIL_PORT = env.int('EMAIL_PORT', default=587)
EMAIL_HOST_USER = env('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD', default='')
EMAIL_USE_TLS = env.bool('EMAIL_USE_TLS', default=True)

# Performance settings
if not DEBUG:
    DATABASES['default']['CONN_MAX_AGE'] = 600

# ========== FIX FOR PYTHON 3.14 RECURSION ERROR ==========
# Fix logging recursion issue in Python 3.14
logging.basicConfig(force=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    # Prevent recursive logging
    'incremental': True,
}