# Generated by Django 6.0.2 on 2026-02-20 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_payments', '0001_initial'),
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatepayment',
            name='new_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='candidatepayment',
            name='previous_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='candidatepayment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('mobile_money', 'Mobile Money'), ('cheque', 'Cheque'), ('loan', 'Loan')], max_length=20),
        ),
        migrations.AlterField(
            model_name='candidatepayment',
            name='payment_type',
            field=models.CharField(choices=[('registration', 'Registration'), ('medical', 'Medical'), ('visa', 'Visa'), ('ticket', 'Ticket'), ('balance', 'Balance Payment'), ('loan_disbursement', 'Loan Disbursement')], max_length=20),
        ),
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField()),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partially Paid'), ('paid', 'Paid'), ('overdue', 'Overdue')], default='pending', max_length=20)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_history', to='candidates.candidate')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='candidate_payments.candidatepayment')),
            ],
            options={
                'ordering': ['due_date'],
            },
        ),
    ]
