# Generated by Django 6.0.2 on 2026-03-02 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_payments', '0003_alter_paymenthistory_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatepayment',
            name='receipt_file',
            field=models.FileField(blank=True, null=True, upload_to='payment_receipts/'),
        ),
        migrations.AddField(
            model_name='candidatepayment',
            name='receipt_uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
